use v6;
use Test;
plan 3;

use PDF::Tags;
use PDF::Tags::Elem;
use PDF::Style::Body;
use PDF::Style::Element;
use CSS::TagSet::TaggedPDF;
use CSS::Properties;
use PDF::Class;
my PDF::Class $pdf .= new;
my PDF::Style::Body $body .= new;
my $page = $body.decorate: $pdf.add-page;
my CSS::TagSet::TaggedPDF $styler .= new;
my PDF::Tags $tags .= create: :$pdf, :$styler;
my PDF::Tags::Elem $doc = $tags.Document;
my PDF::Tags::Elem $header = $doc.Header1;
my PDF::Tags::Elem $figure = $doc.Figure: :Alt("light bulb");
my $elem = $body.element: :text("Tagged/Styled PDF Demo"), :tag($header);
ok $elem.tag.defined;
isa-ok $elem.tag, 'PDF::Tags::Elem';
.render($page.gfx, 10, 750) with $elem;
my Str $image = "t/images/snoopy-happy-dance.jpg";
my CSS::Properties() $css = "opacity:0.5";
my $image-elem = $body.element(:$image, :tag($figure), :$css);
.render($page.gfx, 10, 550) with $image-elem;
lives-ok {$pdf.save-as: "t/tagged.pdf"};
